apiVersion: v1
kind: Service
metadata:
  name: netflix-app
  labels:
    app: netflix-app
spec:
  selector:
    app: netflix-app
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 30007
  type: LoadBalancer
